### ISSUE TITLE
32 bit support?

### ISSUE THREAD

**Issue by dan2wik** [ohnx/nyan-load#1]
I tried to compile this on my 32bit netbook and it was unable to finish building:
make: *** No rule to make target 'glue/ia32/relocation_func.o', needed by 'nyanload.so'.  Stop.

What I believe this is trying to say is the 32bit version of that library is missing.

**Comment by ohnx** [comment]
haha thanks for letting me know that there are still 32-bit systems on this planet :')

I will look into getting the 32 bit stuff.

**Comment by ohnx** [comment]
Probably a little bit of copy-paste from https://github.com/vathpela/gnu-efi/tree/master/gnuefi :)

**Comment by ohnx** [comment]
Hey so I copied over the files, but I'm not sure if there are any more changes needed...

Can you test it? `make` should work now :)

If you want to virtualize nyan-load, you will need to replace `qemu-system-x86_64` on line 34 of the Makefile with `qemu-system-i386`. Also, you will need to get the 32-bit version of OVMF.fd - not sure where you can find it, but https://github.com/tianocore/tianocore.github.io/wiki/OVMF should be a start 📦 

Let me know if you have any troubles! :)

**Comment by dan2wik** [comment]
It is still failing with the same error.

**Comment by ohnx** [comment]
I apparently forgot how to spell... Please pull and try again.

**Comment by ohnx** [comment]
Also, OVMF is apparently a package in apt-get now, so see if you can download that and use it... place it in the root directory.
